# Generated by Django 4.1 on 2022-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('backed_projects', models.IntegerField(blank=True, null=True)),
                ('amount_spent', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Creator', 'Creator'), ('Investor', 'Investor')], max_length=20)),
            ],
        ),
    ]
