# Generated by Django 4.1 on 2022-08-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
